# fish adjusted version of script generated by `github-copilot-cli alias -- "$0"`

function copilot_what-the-shell
    set TMPFILE $(mktemp);
    trap 'rm -f $TMPFILE' EXIT;
    if /opt/homebrew/bin/github-copilot-cli what-the-shell "$argv" --shellout $TMPFILE
      if [ -e "$TMPFILE" ]
        set FIXED_CMD $(cat $TMPFILE);
        eval "$FIXED_CMD"
      else
        echo "Apologies! Extracting command failed"
      end
    else
      return 1
    end
end
alias '!!'='copilot_what-the-shell';

function copilot_git-assist
    set TMPFILE $(mktemp);
    trap 'rm -f $TMPFILE' EXIT;
    if /opt/homebrew/bin/github-copilot-cli git-assist "$argv" --shellout $TMPFILE
      if [ -e "$TMPFILE" ]
        set FIXED_CMD $(cat $TMPFILE);
        eval "$FIXED_CMD"
      else
        echo "Apologies! Extracting command failed"
      end
    else
      return 1
    end
end
alias 'git!'='copilot_git-assist';

function copilot_gh-assist
    set TMPFILE $(mktemp);
    trap 'rm -f $TMPFILE' EXIT;
    if /opt/homebrew/bin/github-copilot-cli gh-assist "$argv" --shellout $TMPFILE
      if [ -e "$TMPFILE" ]
        set FIXED_CMD $(cat $TMPFILE);
        eval "$FIXED_CMD"
      else
        echo "Apologies! Extracting command failed"
      end
    else
      return 1
    end
end
alias 'gh!'='copilot_gh-assist';
alias 'wts'='copilot_what-the-shell';
