has() {
  command -v "$1" 1>/dev/null 2>&1
}

if [ -r /usr/share/zsh/share/antigen.zsh ]; then
  source /usr/share/zsh/share/antigen.zsh
elif [ -r "$HOME"/.local/share/zsh/share/antigen.zsh ]; then
  source "$HOME"/.local/share/zsh/share/antigen.zsh
fi

if has antigen; then
  antigen use oh-my-zsh
  antigen bundle git
  antigen bundle colored-man-pages

  antigen bundle zsh-users/zsh-syntax-highlighting
  antigen bundle zsh-users/zsh-autosuggestions

  antigen apply
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME"/bin ] ; then
    export PATH="$HOME"/bin:$PATH
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME"/.local/bin ] ; then
    export PATH="$HOME"/.local/bin:$PATH
fi

if [ -r /usr/share/fzf/key-bindings.zsh ]; then
    source /usr/share/fzf/key-bindings.zsh
elif [ -r "$HOME"/.local/share/zsh/share/fzf-key-bindings.zsh ]; then
    source "$HOME"/.local/share/zsh/share/fzf-key-bindings.zsh
fi

if [ -r "$HOME"/.linuxbrew/bin/brew ]; then
    eval "$("$HOME"/.linuxbrew/bin/brew shellenv)"
fi

if has zoxide; then
    eval "$(zoxide init zsh)"
fi

if has nvim; then
  export EDITOR='nvim'
elif has vim; then
  export EDITOR='vim'
elif has vi; then
  export EDITOR='vi'
fi

alias e=\"\$EDITOR\"
alias v=\"\$EDITOR\"

if [ "$TERM" = "xterm-kitty" ] && whence kitty &>/dev/null; then
    alias ssh="kitty +kitten ssh"
    alias icat="kitty +kitten icat"
    alias diff="kitty +kitten diff"
elif [ "$TERM" = "foot" ]; then
    alias ssh="TERM=xterm-256color ssh"
fi

if has xdg-open && has setsid; then
    alias open="setsid xdg-open"
fi

if has op; then
    function op-session() {
        eval "$(op signin)"
    }
    function op-exec() {
        op "$@" --session="$(op signin my --raw)"
    }
fi

# Allow local customizations in the ~/.zshrc_local file
if [ -r "$HOME"/.zshrc_local ]; then
    source "$HOME"/.zshrc_local
fi

if has starship; then
    eval "$(starship init zsh)"
fi
