has() {
    type "$1" &>/dev/null
}

if [ -z "$LANG" ]; then
    export LANG=en_US.UTF-8
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME"/.local/bin ] ; then
    export PATH="$HOME"/.local/bin:$PATH
fi

if has zoxide; then
    eval "$(zoxide init zsh)"
fi

if has nvim; then
    export EDITOR='nvim'
elif has vim; then
    export EDITOR='vim'
elif has vi; then
    export EDITOR='vi'
fi

alias e=$EDITOR
alias v=$EDITOR

# Allow local customizations in the ~/.zshrc_local file
if [ -r "$HOME"/.zshrc.local ]; then
    source "$HOME"/.zshrc.local
fi

if has starship; then
    eval "$(starship init zsh)"
fi
