# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    export PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    export PATH="$HOME/.local/bin:$PATH"
fi
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="gentoo"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=45

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git colored-man-pages zsh-autosuggestions zsh-syntax-highlighting)

if [ -r $ZSH/oh-my-zsh.sh ]; then
    source "$ZSH/oh-my-zsh.sh"
fi

if [ -r /usr/share/fzf/key-bindings.zsh ]; then
    source /usr/share/fzf/key-bindings.zsh
fi
if [ -r /usr/share/fzf/completion.zsh ]; then
    source /usr/share/fzf/completion.zsh
fi

if [ -r /usr/share/z/z.sh ]; then
    source /usr/share/z/z.sh
fi

if [ -r $HOME/.linuxbrew/bin/brew ]; then
    eval "$($HOME/.linuxbrew/bin/brew shellenv)"
fi

# User configuration

export EDITOR='nvim'

alias e=\"\$EDITOR\"
alias v=\"\$EDITOR\"

if [ "$TERM" = "xterm-kitty" ] && whence kitty &>/dev/null; then
    alias ssh="kitty +kitten ssh"
    alias icat="kitty +kitten icat"
    alias diff="kitty +kitten diff"
fi

if whence xdg-open &>/dev/null && whence setsid &>/dev/null; then
    alias open="setsid xdg-open"
fi

# Allow local customizations in the ~/.zshrc_local file
if [ -r ~/.zshrc_local ]; then
    source ~/.zshrc_local
fi
