inherits = "github_dark"

"markup.list" = "scale.red.3"
"markup.quote" = "scale.blue.1"
"markup.raw" = "scale.blue.1"

"ui.text" = { fg = "fg.default" }
"ui.text.focus" = { fg = "fg.onEmphasis", bg = "canvas.overlay" }
