" vim:foldmethod=marker

scriptencoding utf-8

" options {{{

set termguicolors

colorscheme rose-pine-dark
syntax enable

set tabstop=2
set shiftwidth=0 " 0 => use same value as tabstop
set expandtab
set smartindent
filetype plugin indent on

set listchars=trail:·,nbsp:_,tab:\ \ 
set list
set shortmess+=tIc
set showcmd
set noshowmode
set ignorecase
set smartcase
set signcolumn=yes
set diffopt+=iwhite
set scrolloff=5
set undofile
set completeopt=menuone,noselect
set updatetime=250
set clipboard=unnamedplus
set spelllang=en_us,de_de

set wildmenu

" }}}

" GUI {{{

set guifont=JetBrains\ Mono\ Symbols:h13

" }}}

" mappings {{{

let mapleader = "\<Space>"
let maplocalleader = "\<Space>"

" }}}
